version: '3'

services:
  concourse-db:
    image: postgres
    container_name: db
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_PASSWORD=concourse_pass
    - POSTGRES_USER=concourse_user
    - PGDATA=/database

  concourse-web:
    image: concourse/concourse
    container_name: web
    command: web
    links: [concourse-db]
    depends_on: [concourse-db]
    expose: ["8080"]
    volumes: ["./keys/web:/concourse-keys"]
    env_file: .added_env
    ports: ["8080:8080"]
    restart: always
    environment:
    - CONCOURSE_POSTGRES_HOST=concourse-db
    - CONCOURSE_POSTGRES_USER=concourse_user
    - CONCOURSE_POSTGRES_PASSWORD=concourse_pass
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL=${CONCOURSE_EXTERNAL_URL}
    - CONCOURSE_BASIC_AUTH_USERNAME=concourse
    - CONCOURSE_BASIC_AUTH_PASSWORD=concourse
    - CONCOURSE_ADD_LOCAL_USER=admin:admin
    - CONCOURSE_MAIN_TEAM_ALLOW_ALL_USERS=true
    - CONCOURSE_MAIN_TEAM_LOCAL_USER=admin

  concourse-worker:
    image: concourse/concourse
    command: worker
    privileged: true
    restart: always
    links: [concourse-web]
    depends_on: [concourse-web]
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
    - CONCOURSE_TSA_HOST=concourse-web:2222
    - CONCOURSE_GARDEN_NETWORK

networks:
  default:
    external:
      name: common_link
